interface Articles {
    user:any,
    categorie:any,
    type_activite:any,
    type_offre:any,
    lib_article:any,
    description:any,
    quantite:any,
    prix:any,
    unite:any,
    slug:any,
    image1:any,
    image2:any,
    image3:any,
    like:any,
    vue:any,
    url:any,
    id:any
}